[build.processing]
  skip_processing = false

[build.processing.html]
  minify = true

[build.processing.css]
  minify = true

[build.processing.js]
  minify = true

[build.processing.images]
  compress = true

[[redirects]]
from = "/"
to = "/endsars"
status = 302